### ISSUE TITLE
Testing Notifications

### ISSUE THREAD

**Issue by jdorfman** [curiefense/media#6]
My notifications are not working, I reset everything and hopefully, it's fixed.

**Comment by sergioarmgpl** [comment]
Hi

**Comment by jdorfman** [comment]
@sergioarmgpl can you send another message please?

**Comment by sergiopsyalo** [comment]
hi

**Comment by sergiopsyalo** [comment]
@jdorfman hi

**Comment by jdorfman** [comment]
@sergioarmgpl ty that worked
